homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa Gandia
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml


binary_sensor:
  - platform: skybell
    monitored_conditions:
      - button
      - motion
  

camera:
  - platform: yi
    name: salon
    host: '192.168.86.20'
    password: !secret password_camera_salon
    #path: /tmp/sd/record
    #ffmpeg_arguments: '-vf scale=800:450'  
  - platform: skybell  
  - platform: mjpeg
    name: entrada
    mjpeg_url: http://192.168.86.42/video/mjpg.cgi
    still_image_url: http://192.168.86.42/image/jpeg.cgi
    username: !secret user_camera_entrada
    password: !secret password_camera_entrada  
  - platform: yi
    name: kitchen
    host: '192.168.86.21'
    password: !secret password_camera_kitchen
    path: /tmp/sd/record
  - platform: yi
    name: exterior_trasera
    host: '192.168.86.152'
    password: !secret password_camera_ext_trasera
    path: /tmp/sd/record  
cloud:
  google_actions:
    filter:
      include_domains:
        - cover
        - switch
        - light
        - input_boolean
      exclude_entities:
        - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_2
        #- switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_3
        - switch.switch_2
        - switch.switch_3
        - switch.switch_4
        - switch.switch_5
        - switch.switch_6
        - switch.switch_7
        - switch.switch_8
        - switch.switch_9
        - switch.switch_10
        - switch.switch_11
        - switch.switch_12
        - switch.switch_14
        - switch.switch_15
        - switch.switch_17
        - switch.switch_18
        - switch.switch_19
        - switch.switch_20
        - switch.switch_21
        - switch.switch_23
        - switch.switch_24
        - switch.qubino_zmnhcdx_flush_shutter_switch
        - switch.qubino_zmnhcdx_flush_shutter_switch_2
        - switch.qubino_zmnhcdx_flush_shutter_switch_3
        - switch.qubino_zmnhcdx_flush_shutter_switch_4
        - cover.switch_2
        - cover.switch_3
        - cover.switch_4
        - cover.switch_5
        - cover.switch_6
        - cover.switch_7
        - cover.switch_8
        - cover.switch_9
        - cover.switch_10
        - cover.switch_11
        - cover.switch_12
        - cover.switch_13 
        - cover.switch_14
        - cover.qubino_zmnhcdx_flush_shutter_switch
        - cover.qubino_zmnhcdx_flush_shutter_switch_2
        - cover.qubino_zmnhcdx_flush_shutter_switch_3
        - cover.qubino_zmnhcdx_flush_shutter_switch_4
        - switch.qubino_zmnhbdx_flush_2_relays_switch_7
        - switch.qubino_zmnhbdx_flush_2_relays_switch_8
        - switch.qubino_zmnhbdx_flush_2_relays_switch_10
        - switch.qubino_zmnhbdx_flush_2_relays_switch_15
        - switch.qubino_zmnhbdx_flush_2_relays_switch_18
        - light.fibaro_system_fgd212_dimmer_2_level
        - input_boolean.ya_informado
# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:



# Enables configuration UI
config:
# Show links to resources in log and frontend

cover:
  - platform: group
    name: habitacion_1
    entities:
      - cover.level_4 #persiana 1
      - cover.qubino_zmnhcdx_flush_shutter_level_4 #- cover.level_3 #persiana 2 habitación princpal
  - platform: group
    name: habitacion_patri
    entities:
      - cover.level_8 #Patri persiana 1
      - cover.qubino_zmnhcdx_flush_shutter_level_3 #Patri persiana 2, antes cover.level_7
  - platform: group
    name: salon
    entities:
      - cover.qubino_zmnhcdx_flush_shutter_level #persiana salón 1 - antes cover.level_5 
      - cover.level_10 #persiana salón 2 
      - cover.level_9 # persiana salón 3
      - cover.level_6  # persiana salón 4
  - platform: group
    name: cocina
    entities: #se deja la persiana cocina 2 de salida intencionadamente fuera del grupo
      - cover.level_12 #persian cocina 1 
      - cover.level #persian cocina 3
      - cover.level_13 #persian cocina 4
      - cover.level_14 #persiana aseo    


device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
  - platform: ping
    hosts:
      jorge_mate10_ping: 192.168.86.32
      blanca_mi_A1_ping: 192.168.86.25
      patricia_axon7mini_ping: 192.168.86.33


# Discover some devices automatically
discovery:

duckdns:
  domain: jolaca01
  access_token: !secret duckdns_access_token

ffmpeg:

# Enables the frontend
frontend:

google:
  client_id: !secret google_client_id 
  client_secret: !secret google_client_secret 




# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - group.main_weather
      - group.main_weather_4days_forecast

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  ssl_certificate: !secret ssl_certificate 
  ssl_key: !secret ssl_key 
  base_url: !secret base_url 


#ifttt:  
#  key: !secret ifttt_key 


input_boolean:
  ya_informado:
    name: Indica si ya se ha dado info matinal
    initial: off
    icon: mdi:radio
  alarma_activada:
    name: Alarma activada
    initial: off
    icon: mdi:alarm-light

input_number:
  cinema_slider:
    name: CinemaLEDs_speed
    initial: 150
    min: 0
    max: 150
    step: 10  
    mode: slider  
  cinema_slider2:
    name: CinemaLED2_speed
    initial: 150
    min: 0
    max: 150
    step: 10  
    mode: slider  

light:  
  - platform: skybell
  - platform: mqtt_json
    name: "CinemaLEDs"
    state_topic: "leds/cine"
    command_topic: "leds/cine/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    name: "CinemaLED2"
    state_topic: "leds/cine2"
    command_topic: "leds/cine2/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: group
    name: CinemaLights
    entities:
      - light.CinemaLEDs
      - light.CinemaLED2

# View all events in a logbook
logbook:

logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning


# Enables a map showing the location of tracked devices
map:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

mqtt:
  broker: m23.cloudmqtt.com
  port: 15523
  client_id: HAconnection
  keepalive: 60
  username: !secret mqtt_username 
  password: !secret mqtt_password 

nest: # Nest Thermostat
  client_id: !secret nest_client_id 
  client_secret: !secret nest_client_secret 

notify:
  - name: My_notifier
    platform: html5
    gcm_api_key: !secret gcm_api_key 
    gcm_sender_id: !secret gcm_sender_id 

sensor:  
  - platform: fail2ban
    jails:
      - ssh
      - hass-iptables
    scan_interval: 360  
  - platform: synologydsm
    host: 192.168.86.39
    username: !secret synology_username 
    password: !secret synology_password
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - memory_available_real
      - network_up
      - network_down
      - volume_status
      - disk_status
      - disk_smart_status
      - disk_temp
  - platform: google_wifi
    host: 192.168.86.1
    monitored_conditions:
      - current_version
      - new_version
      - uptime
      - last_restart
      - status
  - platform: skybell
    monitored_conditions:
      - chime_level
  - platform: google_travel_time
    name: home to work
    api_key: !secret google_travel_time_api_key 
    origin: zone.home
    destination: zone.oficina
    options:
      units: metric
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
  - platform: google_travel_time
    name: home_to_work
    api_key: !secret google_travel_time_api_key 
    origin: zone.home
    destination: zone.oficina
    scan_interval: 3600 #intervalo de polling en segundos. 
    options:
      units: metric
  - platform: wunderground
    api_key: !secret wunderground_api_key 
    lang: SP
    monitored_conditions:
      - temp_c
      - temp_high_record_c
      - temp_high_1d_c
      - temp_low_1d_c
      - temp_low_record_c
      - feelslike_c
      - feelslike_string
      - heat_index_string
      - precip_today_metric
      - precip_today_string
      - precip_1d
      - wind_kph
      - wind_1d_kph
      - wind_string
      - pressure_mb
      - pressure_trend
      - relative_humidity
      - solarradiation
      - alerts
      - weather_1d_metric
      - weather_1n_metric
      - weather_2d_metric
      - weather_2n_metric
      - weather_3d_metric
      - weather_3n_metric
      - weather_4d_metric
      - weather_4n_metric
  - platform: template
    sensors:
      proximo_evento:
        friendly_name: 'proximo_evento'
        value_template: "{{ states.calendar.jolaca01gmailcom.attributes.message }}"
      proximo_evento_es_allday:
        value_template: "{{ states.calendar.jolaca01gmailcom.attributes.all_day }}"
      proximo_evento_empieza:
        value_template: "{{ states.calendar.jolaca01gmailcom.attributes.start_time }}"
      proximo_cumple:
        friendly_name: 'Cumples_conocidos'
        value_template: "{{ states.calendar.contacts.attributes.message }}"
      proximo_cumple_empieza:
        value_template: "{{ states.calendar.contacts.attributes.start_time }}"
      neo_coolcam_battery_water_detector_cocina:
        friendly_name: 'Battery detector inundación cocina'
        unit_of_measurement: '%'
        entity_id:  zwave.neo_coolcam_water_leakage_detector
        value_template: >-
          {% if states.zwave.neo_coolcam_water_leakage_detector %}
            {{ states.zwave.neo_coolcam_water_leakage_detector.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
      neo_coolcam_battery_water_detector_bany_principal:
        friendly_name: 'Battery detector inundación baño 1'
        unit_of_measurement: '%'
        entity_id:  zwave.neo_coolcam_water_leakage_detector_2
        value_template: >-
          {% if states.zwave.neo_coolcam_water_leakage_detector_2 %}
            {{ states.zwave.neo_coolcam_water_leakage_detector_2.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}  
      neo_coolcam_battery_water_detector_bany_azul:
        friendly_name: 'Battery detector inundación baño azul'
        unit_of_measurement: '%'
        entity_id:  zwave.neo_coolcam_water_leakage_detector_3
        value_template: >-
          {% if states.zwave.neo_coolcam_water_leakage_detector_3 %}
            {{ states.zwave.neo_coolcam_water_leakage_detector_3.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %} 
      neo_coolcam_battery_water_detector_aseo:
        friendly_name: 'Battery detector inundación aseo'
        unit_of_measurement: '%'
        entity_id:  zwave.neo_coolcam_water_leakage_detector_4
        value_template: >-
          {% if states.zwave.neo_coolcam_water_leakage_detector_4 %}
            {{ states.zwave.neo_coolcam_water_leakage_detector_4.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}     
      neo_coolcam_battery_recibidor:
        friendly_name: 'Battery recibidor'
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_battery_powered_pir_sensor
        value_template: >-
          {% if states.zwave.neo_coolcam_battery_powered_pir_sensor %}
            {{ states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
      neo_coolcam_battery_comedor:
        friendly_name: 'Battery comedor'
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_battery_powered_pir_sensor_2
        value_template: >-
          {% if states.zwave.neo_coolcam_battery_powered_pir_sensor_2 %}
            {{ states.zwave.neo_coolcam_battery_powered_pir_sensor_2.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
      neo_coolcam_battery_salon:
        friendly_name: 'Battery salon'
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_battery_powered_pir_sensor_3
        value_template: >-
          {% if states.zwave.neo_coolcam_battery_powered_pir_sensor_3 %}
            {{ states.zwave.neo_coolcam_battery_powered_pir_sensor_3.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
      neo_coolcam_battery_pasillo:
        friendly_name: 'Battery pasillo'
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_battery_powered_pir_sensor_4    
        value_template: >-
          {% if states.zwave.neo_coolcam_battery_powered_pir_sensor_4 %}
            {{ states.zwave.neo_coolcam_battery_powered_pir_sensor_4.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
      neo_coolcam_battery_cocina:
        friendly_name: 'Battery cocina'
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_battery_powered_pir_sensor_7
        value_template: >-
          {% if states.zwave.neo_coolcam_battery_powered_pir_sensor_7 %}
            {{ states.zwave.neo_coolcam_battery_powered_pir_sensor_7.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
      neo_coolcam_battery_cine:
        friendly_name: 'Battery cine'
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_battery_powered_pir_sensor_8
        value_template: >-
          {% if states.zwave.neo_coolcam_battery_powered_pir_sensor_8 %}
            {{ states.zwave.neo_coolcam_battery_powered_pir_sensor_8.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
      neo_coolcam_battery_entrada:
        friendly_name: 'Battery entrada'
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_battery_powered_pir_sensor_9
        value_template: >-
          {% if states.zwave.neo_coolcam_battery_powered_pir_sensor_9 %}
            {{ states.zwave.neo_coolcam_battery_powered_pir_sensor_9.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
      neo_coolcam_battery_garaje:
        friendly_name: 'Battery garaje'
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_battery_powered_pir_sensor_6
        value_template: >-
          {% if states.zwave.neo_coolcam_battery_powered_pir_sensor_6 %}
            {{ states.zwave.neo_coolcam_battery_powered_pir_sensor_6.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
      neo_coolcam_battery_puerta_garaje:
        friendly_name: 'Battery puerta garaje'
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_doorwindow_detector
        value_template: >-
          {% if states.zwave.neo_coolcam_doorwindow_detector %}
            {{ states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level }}
          {% else %}
            '0'
          {% endif %}
shell_command:
  set_ids_permissions: chmod 0744 /var/log/fail2ban.log

skybell: # Enables SkyBell HD
  username: !secret skybell_username 
  password: !secret skybell_password

# Track the sun
sun: 

switch:
  - platform: skybell
    monitored_conditions:
      - do_not_disturb
      - motion_sensor

timer:
  puerta_garaje:
    duration: '00:01:30'


tts: # Text to speech
  #- platform: voicerss
  #  api_key: !secret voicerss_api_key 
  #  language: 'es-es'
  #  codec: 'mp3'
  #  format: '44khz_16bit_stereo'
  - platform: google
    language: 'es-es'



zwave:
  usb_path: /dev/ttyACM0
  #network_key: !secret network_key 

zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
